### ISSUE TITLE
Can't add a child node to a leaf

### ISSUE THREAD

**Issue by nite** [teleport/react-dnd-treeview#4]
In your example, remove B1 & B2, then nothing can be added to B, nor any other leaf node - dragging onto a leaf not can only make it a sibling.

**Comment by bsjaffer** [comment]
i am also facing same issue .. any solution as of now?? if there is no child node then we cant add a node as child

**Comment by magnushiie** [comment]
I have a fix in progress for this, hope to be able to push it later today.

**Comment by DC-development** [comment]
Is this fixed? Demo seems broken still.

**Comment by magnushiie** [comment]
Apologies, I had fixed this in November already, but mentioned the wrong issue number (#5), and also had forgotten to update the example build output. The example is now updated and should work.
