### ISSUE TITLE
No start-script in Package.json

### ISSUE THREAD

**Issue by DC-development** [teleport/react-dnd-treeview#7]
Docs say `cd example && npm install && npm start` but there is no start-script, so it errs at:
`npm ERR! missing script: start`

**Comment by magnushiie** [comment]
There is a start script in example/package.json. Can you see whether invoking `npm start` from that directory directly would work?

**Comment by DC-development** [comment]
ups - my bad - Im sure it does - overlooked the example dir, sorry for wasting your time

**Comment by magnushiie** [comment]
No problem, closing then
